# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  default

resources:
  repositories:
  - repository: test
    type: github
    name: ebogatenkov/test
    ref: refs/heads/main
    endpoint: githubPAT
  - repository: ado
    type: git
    name: proj
    trigger:
     branches:
       include: [main]

trigger:
 none
pr:
 none

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
